name: maheksync
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  provider: ^6.1.5+1
  country_code_picker: ^3.4.1
  nb_utils: ^7.2.0
  cloud_firestore: ^6.3.0
  flutter_svg: ^2.2.4
  firebase_auth: ^6.4.0
  uuid: ^4.5.3
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  firebase_app_check: ^0.4.3
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  firebase_core:
  lottie: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animation/
    - assets/icons/

  fonts:
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF

    - family: SFProDisplayMedium
      fonts:
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF

    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

    - family: SFProDisplayBlackItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          style: italic

    - family: SFProDisplayHeavyItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic

    - family: SFProDisplayLightItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic

    - family: SFProDisplaySemiBoldItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic

    - family: SFProDisplayThinItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          style: italic

    - family: SFProDisplayUltraLightItalic
      fonts:
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic