// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_M9fS2xarXchcv3xZ_j1wu1bZr-5t1ms',
    appId: '1:75271763799:web:0757da4034eaeedf843012',
    messagingSenderId: '75271763799',
    projectId: 'maheksync',
    authDomain: 'maheksync.firebaseapp.com',
    storageBucket: 'maheksync.firebasestorage.app',
    measurementId: 'G-FWCMG7CE8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcc5fohwSGiMtehVGTZGbGv1liVVILttg',
    appId: '1:75271763799:android:acaa4cd19c4ce0c3843012',
    messagingSenderId: '75271763799',
    projectId: 'maheksync',
    storageBucket: 'maheksync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpgKLX2ltnEj1F_v690-FshhfL3SgMnw',
    appId: '1:75271763799:ios:e3b9e47eeba355a4843012',
    messagingSenderId: '75271763799',
    projectId: 'maheksync',
    storageBucket: 'maheksync.firebasestorage.app',
    iosBundleId: 'com.mahek.maheksync',
  );
}
