part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const LOGIN_SCREEN = _Paths.LOGIN_SCREEN;
  static const AUTH = _Paths.AUTH;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const MY_DEVICES = _Paths.MY_DEVICES;
  static const WARRANTY_TRACKER = _Paths.WARRANTY_TRACKER;
  static const EXPENSES = _Paths.EXPENSES;
  static const SETTINGS = _Paths.SETTINGS;
  static const SUPPORT = _Paths.SUPPORT;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const ADD_NEW_DEVICES = _Paths.ADD_NEW_DEVICES;
  static const VIEW_DEVICES = _Paths.VIEW_DEVICES;
  static const POLICY_SETTINGS = _Paths.POLICY_SETTINGS;
  static const ADMIN_PROFILE = _Paths.ADMIN_PROFILE;
  static const PAYEMENT_METHOD = _Paths.PAYMENT_METHODS;
  static const CATEGORIES = _Paths.CATEGORIES;
  static const MY_PURCHASES = _Paths.MY_PURCHASES;
  static const ADD_EDIT_PURCHASE = _Paths.ADD_EDIT_PURCHASE;
  static const MY_PURCHASES_DETAILS = _Paths.MY_PURCHASES_DETAILS;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
  static const CRUD_SUBSCRIPTION = _Paths.CRUD_SUBSCRIPTION;
  static const SUBSCRIPTION_DETAILS = _Paths.SUBSCRIPTION_DETAILS;
  static const SUBSCRIPTION_CRUD = _Paths.SUBSCRIPTION_CRUD;
  static const REMINDER = _Paths.REMINDER;
  static const REMINDER_CRUD = _Paths.REMINDER_CRUD;
  static const DUES_TRACKER = _Paths.DUES_TRACKER;
  static const PERSONAL_TASKS = _Paths.PERSONAL_TASKS;
  static const PERSONAL_TASK_CRUD = _Paths.PERSONAL_TASK_CRUD;
  static const AEGIS = _Paths.AEGIS;
  static const AEGIS_FORM = _Paths.AEGIS_FORM;
  static const SMART_MAP_DASHBOARD = _Paths.SMART_MAP_DASHBOARD;
  static const MY_CONTACTS = _Paths.MY_CONTACTS;
  static const GENERATE_BILL = _Paths.GENERATE_BILL;
  static const GENERATE_BILL_CREATE = _Paths.GENERATE_BILL_CREATE;
  static const GENERATE_BILL_PREVIEW = _Paths.GENERATE_BILL_PREVIEW;
  static const IMAGE_TO_TEXT = _Paths.IMAGE_TO_TEXT;
  static const MOVIES = _Paths.MOVIES;
  static const ALL_MOVIES = _Paths.ALL_MOVIES;
  static const MOVIE_CRUD = _Paths.MOVIE_CRUD;
  static const MOVIE_DETAILS = _Paths.MOVIE_DETAILS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH_SCREEN = '/splash-screen';
  static const LOGIN_SCREEN = '/login-screen';
  static const AUTH = '/auth';
  static const DASHBOARD = '/dashboard';
  static const MY_DEVICES = '/dashboard/my-devices';
  static const WARRANTY_TRACKER = '/dashboard/warranty-tracker';
  static const EXPENSES = '/dashboard/expenses';
  static const SETTINGS = '/dashboard/settings';
  static const SUPPORT = '/dashboard/support';
  static const SIGN_UP = '/sign-up';
  static const ADD_NEW_DEVICES = '/add-new-devices';
  static const VIEW_DEVICES = '/view-devices';
  static const POLICY_SETTINGS = '/policy-settings';
  static const ADMIN_PROFILE = '/admin-profile';
  static const PAYMENT_METHODS = '/dashboard/payment-methods';
  static const CATEGORIES = '/dashboard/categories';
  static const MY_PURCHASES = '/dashboard/my-purchases';
  static const ADD_EDIT_PURCHASE = '/add-edit-purchase';
  static const MY_PURCHASES_DETAILS = '/my-purchases-details';
  static const SUBSCRIPTION = '/dashboard/subscriptions';
  static const CRUD_SUBSCRIPTION = '/crud-subscription';
  static const SUBSCRIPTION_DETAILS = '/dashboard/subscription-details';
  static const SUBSCRIPTION_CRUD = '/subscription-crud';
  static const REMINDER = '/dashboard/reminders';
  static const REMINDER_CRUD = '/reminder-crud';
  //check
  static const DUES_TRACKER = '/dues-tracker';
  static const PERSONAL_TASKS = '/dashboard/personal-tasks';
  static const PERSONAL_TASK_CRUD = '/personal-task-crud';
  static const AEGIS = '/dashboard/aegis';
  static const AEGIS_FORM = '/aegis-form';
  static const SMART_MAP_DASHBOARD = '/smart-map-dashboard';
  static const MY_CONTACTS = '/my-contacts';
  static const GENERATE_BILL = '/generate-bill';
  static const GENERATE_BILL_CREATE = '/generate-bill-create';
  static const GENERATE_BILL_PREVIEW = '/generate-bill-preview';
  static const IMAGE_TO_TEXT = '/dashboard/image-to-text';
  static const MOVIES = '/dashboard/movies';
  static const ALL_MOVIES = '/all-movies';
  static const MOVIE_CRUD = '/movie-crud';
  static const MOVIE_DETAILS = '/movie-details';
}
